### ISSUE TITLE
Problem with dragging a tab from another window

### ISSUE THREAD

**Issue by Teasday** [nyordanov/panorama#2]
I saw a comment about fixing support for multiple windows in the release notes, but I wonder if this particular issue was included in that. I'll report it anyway.

If you have two separate windows open and drag a tab from window B to window A, the expected outcome is that the dragged-in tab is now a part of the current tab group in A. What actually seems to happen is that the tab is not added to the current tab group. In fact, unfortunately changing the tab in window A instantly removes the dragged-in tab entirely.

**Comment by nyordanov** [comment]
Thanks for letting me know, I'll try to fix this in the next update. In the meantime - restarting the browser should give you your missing tabs back.

**Comment by nyordanov** [comment]
Fixed in v0.0.9
