### ISSUE TITLE
ctrl+` to switch groups

### ISSUE THREAD

**Issue by adipose** [nyordanov/panorama#7]
The hotkey from panorama (ctrl+`) does not work.  Is there a group switching hotkey?

**Comment by adipose** [comment]
https://support.mozilla.org/en-US/kb/tab-groups-organize-tabs?redirectlocale=en-US&redirectslug=what-are-tab-groups#w_how-do-i-switch-between-tab-groups

**Comment by bogdan-calapod** [comment]
I think you are wanting something more akin to #8  ?

**Comment by adipose** [comment]
If this shortcut is part of the keyboard shortcuts, then yes!

**Comment by nyordanov** [comment]
I've added an option for setting a keyboard shortcut in v0.0.12. However, the necessary API is only implemented in Firefox 60, so you will need to update to the beta before you can use the new option.

"Switch to the next group" is not yet implemented, so I will keep this issue open.

**Comment by FrankEBailey** [comment]
+1 for a keyboard shortcut to switch between groups (CTRL+` would be ideal)
