### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by guest73** [nyordanov/panorama#8]
I would like to switch tabs with a keyboard arrow keys.

**Comment by bogdan-calapod** [comment]
It doesn't seem like this extension supports keyboard shortcuts at all - would be nice if the original Panorama shortcuts (Ctrl + Shift + E to open, etc) would be supported, with customization options along the line :) 

I never did Firefox extension work, but if needed, I could look into it and make a PR - it doesn't seem like it would be very difficult.

**Comment by nyordanov** [comment]
I've added an option for setting a keyboard shortcut in v0.0.12. However, the necessary API is only implemented in Firefox 60, so you will need to update to the beta before you can use the new option.

**Comment by guest73** [comment]
Now I am thinking maybe I have expressed my desire wrongly. Sorry about that, always happens to me. What I meant was, I want to activate the panorama view (Ctrl+E is fine with me) then I want to use arrow keys to navigate between tabs(change the selection) and then press Enter to switch to the selected tab. That would be really convenient for "keyboard users". And thanks for your support.

**Comment by nyordanov** [comment]
Ah, I see. I'll reopen this issue then.

**Comment by guest73** [comment]
Thanks.
And also seems like a nice idea to have arrow_keys to navigate tabs withing a single Tab group and something like Ctrl+arrow_keys to navigate groups. But that's just my preference.
